### ISSUE TITLE
Inductor

### ISSUE THREAD

**Issue by ortegafernando** [aplavins/Arduino-MPPT#1]
Hi,

Thanks a lot !!!! Waht about and schema or similar ? I have check other MPPT in instructables and tim lonan, but yours is for 250W, I have a doubt, what inductor do you use?

Best regards

**Comment by aplavins** [comment]
I wound my own 20uH ferrite core inductor with 14awg magnet wire. Schematic
is coming soon!

On Fri, Jun 12, 2015 at 6:24 PM, juan3211 notifications@github.com wrote:

> Hi,
> 
> Thanks a lot !!!! Waht about and schema or similar ? I have check other
> MPPT in instructables and tim lonan, but yours is for 250W, I have a doubt,
> what inductor do you use?
> 
> Best regards
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aplavins/Arduino-MPPT/issues/1.

## 

When there's a smile in your heart
There's no better time to start
Think of all the joy you'll find
When you leave the world behind
And bid your cares good-bye

**Comment by aplavins** [comment]
schematic is up
https://github.com/aplavins/Arduino-MPPT/blob/master/MPPT%20charge%20controller%20barebones.pdf

On Sun, Jun 14, 2015 at 7:57 PM, Adam Plavinskis aplavins@gmail.com wrote:

> I wound my own 20uH ferrite core inductor with 14awg magnet wire.
> Schematic is coming soon!
> 
> On Fri, Jun 12, 2015 at 6:24 PM, juan3211 notifications@github.com
> wrote:
> 
> > Hi,
> > 
> > Thanks a lot !!!! Waht about and schema or similar ? I have check other
> > MPPT in instructables and tim lonan, but yours is for 250W, I have a doubt,
> > what inductor do you use?
> > 
> > Best regards
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/aplavins/Arduino-MPPT/issues/1.
> 
> ## 
> 
> When there's a smile in your heart
> There's no better time to start
> Think of all the joy you'll find
> When you leave the world behind
> And bid your cares good-bye

## 

When there's a smile in your heart
There's no better time to start
Think of all the joy you'll find
When you leave the world behind
And bid your cares good-bye

**Comment by aplavins** [comment]
Here are some links that will allow you to build your own inductor

http://www.ebay.com/itm/22mm-x-14mm-x-8mm-Round-Green-Toroid-Ferrite-Cores-10-Pcs-/271566883360

http://www.ebay.com/itm/Magnet-Wire-14-AWG-Gauge-Enameled-Copper-4oz-155C-20ft-Magnetic-Coil-Winding-/261085726306?pt=LH_DefaultDomain_0&hash=item3cc9ec0662

You can also salvage these components from used power electronics

use this calculator to find out what value inductor you need:
http://www.daycounter.com/Calculators/Switching-Converter-Calculator.phtml

and this one to find the number of turns for the core and wire you have:
http://coil32.net/online-calculators/ferrite-torroid-calculator.html

Mine was 10 turns to get about 20uH

Hope this helps!
